#+TITLE: cljserial
#+AUTHOR: Cormac Cannon
#+EMAIL: cormac.cannon@neuromoddevices.com
#+LANGUAGE: en
#+COPYRIGHT: Neuromod Devices Ltd. 2023
#+DATE: 2023-09-19

# HTML EXPORT SETUP
# 1. Apply a theme
#+SETUPFILE: ~/Documents/templates/org-html-themes/org/theme-readtheorg.setup

# 2. Ensure exports include both source block contents and any results
#+PROPERTY: header-args :exports both

# 3. Specify styles for ODT (and DOCX) export

#+ODT_STYLES_FILE: ("~/Documents/templates/nmd-template.odt" ("styles.xml" "content.xml" "Pictures/1000000000000A4F000004650AA167B89A2F5561.jpg"))

# Startup options : Want to view rendered versions of latex fragments (equations etc.) by default
#+STARTUP:: latexpreview


Some introductory text

* Table of Contents                                         :TOC_4_gh:noexport:
- [[#overview][Overview]]
  - [[#example-deployment][Example deployment]]
  - [[#browser-console-logging][Browser console logging]]
  - [[#source-code-organisation][Source code organisation]]
    - [[#webserial-terminal][WebSerial terminal]]
    - [[#app][app]]
    - [[#html---uix-converter][HTML -> UIx converter]]
  - [[#to-addinvestigate][To add/investigate]]
  - [[#interesting-alternatives][Interesting alternatives]]
  - [[#investigated--not-adopted][Investigated / not adopted]]
  - [[#aws-integration][AWS integration]]
    - [[#services-to-integrate][Services to integrate]]
    - [[#references][References]]
    - [[#aws-local-environment-setup][AWS local environment setup]]
    - [[#aws-dependency-patching--post-installation-steps][AWS dependency patching / post-installation steps]]
- [[#languagelibrary-references][Language/library references]]
- [[#blog-posts-etc][Blog posts etc.]]
- [[#component--style-resources][Component / style resources]]
- [[#build-cheatsheet][Build cheatsheet]]
  - [[#dependencies][Dependencies]]
  - [[#source-materials][Source materials]]
  - [[#initial-setup][Initial setup]]
  - [[#test-build][Test build]]
  - [[#component-driven-development-portfolio-build][Component-driven development (portfolio) build]]
  - [[#production-build][Production build]]
  - [[#combined-development-build-dev-app-unit-test-runner-and-portfolio][Combined development build (dev app, unit test runner and portfolio)]]
  - [[#shadow-cljs-inspect][shadow-cljs inspect]]
- [[#repl-cheatsheet][Repl cheatsheet]]
  - [[#open-a-repl-session-from-a-shell][Open a repl session from a shell]]
  - [[#open-a-repl-session-from-your-editor][Open a repl session from your editor]]
- [[#documenting-code][Documenting code]]
- [[#stack-components][Stack components]]
  - [[#state-management][State management]]
    - [[#application-data-storage-using-refx-re-frame][Application data storage using refx (re-frame)]]
    - [[#hierarchical-state-machines-using-cljs-statecharts][Hierarchical state machines using cljs-statecharts]]
  - [[#testing][Testing]]
    - [[#generative-testing-using-spec-and-spec-test][Generative testing using Spec and Spec test]]
      - [[#links][Links]]
    - [[#candidate-approaches][Candidate approaches]]
      - [[#cljstest-and-react-testing-library][cljs.test and react-testing-library]]
  - [[#css][CSS]]
    - [[#daisyui--portfolio-css-incompatibility][DaisyUI / Portfolio CSS incompatibility]]
  - [[#internationalisation][Internationalisation]]
    - [[#clj-18n][clj-18n]]
    - [[#tempura][tempura]]

* Overview
A my-first-cljs-project implementing the following completely unrelated views/functions:
- A webserial terminal
- A todo app (adapted from the uix-starter example)
- A quick-and-dirty html -> uix syntax converter for integrating html samples grabbed from tailwind site etc.

This is an exploratory effort kicking the tyres of the following technologies:
- [[https://pitch-io.github.io/uix/docs/][UIx2]] :: UI toolkit / wrapper for React
- [[https://shadow-cljs.github.io/docs/UsersGuide.html][shadow-cljs]] :: build system
- [[https://github.com/ferdinand-beyer/refx][refx]] :: UI data store (re-frame using react hooks)
- [[https://github.com/lucywang000/clj-statecharts][clj-statecharts]] :: UI/subsystem state management  (integrated with refx)
- [[https://github.com/cjohansen/portfolio][Portfolio]] :: component-driven development (similar to devcards / storybook.js)
- Metosin [[https://github.com/metosin/m0alli][malli]] :: data schema - selective typing / design-by-contract and generative testing.
- [[https://github.com/lambdaisland/glogi][glogi]] :: logging framework
- [[https://tailwindcss.com/docs/installation][TailwindCSS]] :: utility CSS classes (as a PostCSS plugin)
- [[https://daisyui.com/components/][DaisyUI]] :: pre-built Tailwind components (for instant gratification - but I'm incrementally phasing this out)
- svg icons :: Extracted from the phosphor and/or fontawesome font sets (using two excellent libraries written by Christian Johansen)
- webserial API :: serial port access from the browser

Started with the [[https://github.com/pitch-io/uix-starter][uix-starter]] project from pitch.io (= UIx2 + shadow-cljs), then added the other bits and pieces.

The webserial terminal currently has an optional filter for FTDI devices I'm mostly using when selecting a port.

The included TODO MVC example / widget started out as a synthesis of the excellent examples provided with the UIx2 starter kit and refx - the refx end of things has been simplified / reworked quite a bit in the interest of composability and component-driven development using portfolio.

The yarn config in [[./package.json]] allows the app, test and portfolio builds to be run individually or in parallel.
~yarn all~ will run the app, test and portfolio builds on ports 8080, 8081 and 8082, respectively.

There's plenty here that's only (if even) partly thought through, and likely downright unidiomatic, but it's been useful for me to get a feel for cljs development.

** Example deployment
I've deployed a functional static build of the project here using gitlab ci / gitlab pages:
https://cljserial-cormacc1-0e5f9b68c5dce51c18dfd8ac9fec3118aa93742f32dd.gitlab.io/

Serial terminal functionality working in supported browsers (i.e. chrome, chromium, edge).

N.B. use of webserial requires a secure context (i.e. running locally, or connected remotely via https). This had me puzzled for a while when trying to deploy on a self-hosted gitlab instance without proper certs setup.

Tried a github pages deployment as well, but got some funny errors. If at first you don't succeed, em, give up? For now at least, given that gitlab is my daily driver for work and likely target if I adopt this stack for the day job.

N.B. I've made token efforts at caching dependency folders etc. for the gitlab CI build, but ineffective so far. To be revisited....
See [[./.gitlab-ci.yml]]

** Browser console logging
Pretty console logging via glogi requires custom formatters to have been enabled for your browser dev tools window -- see:
[[https://github.com/binaryage/cljs-devtools/blob/master/docs/installation.md]]

Without this config, the log entries will contain lots of less useful js data structure.


** Source code organisation
Top level:
- entrypoint :: [[./src/cljserial/core.cljs]]

Rather than centralising the data model and refx setup for unrelated functions, functionality has been composed in vertical (hopefully) independent slices.

*** WebSerial terminal
Controller / hardware interface:
- [[./src/cljserial/services/webserial.cljs]] :: The serial port controller -- a clj-statechart state machine integrated with refx
- [[./src/cljserial/utils/webserial.cljs]] :: Cljs interface wrapping the webserial api

UI
- [[./src/cljserial/pages/terminal.cljs]] :: The terminal page / view -- glues together component and refx database
- [[./src/cljserial/components/term.cljs]] :: The UI component.
- [[./portfolio/src/cljserial/components/term_scenes.cljs]] :: The portfolio scenes for the UI widget

*** ToDo app
- [[./src/cljserial/pages/todo_mvc.cljs]] :: The Todo app page / view -- glues together component and refx database
- [[./src/cljserial/components/todo.cljs]]
- [[./src/cljserial/services/todo.cljs]]
- [[./portfolio/src/cljserial/components/todo_scenes.cljs]]

*** HTML -> UIx converter
[[./src/cljserial/pages/converter.cljs]]

** To add/investigate
- [[https://github.com/roman01la/cljs-react-devtools][cljs-react-devtools]] :: Debug utilities by Roman Liutikov (UIx author)
- supabase :: Use this rather than aws amplify for backend?
- Datascript :: integrate with refx -- this needed re-posh when using re-frame, but refx docs suggest that integration with datascript has been considered there already....
- UI string localisation (using ?)
  - maybe [[https://github.com/brightin/pottery][pottery]]?
- automated unit test browser interface using kaocha? Though the shadow-cljs test runner looks fine so far...
- [[https://headlessui.com/][Headless UI]] (component kit from Tailwind Labs)?
- squint cljs -> js compiler :: https://blog.michielborkent.nl/porting-cljs-project-to-squint.html
- [[https://github.com/applied-science/js-interop][js-interop]] library :: js interop not a pain point so far, but keep it in mind...
- [[https://flow-storm.org][flow-storm]] debugger
- [[https://github.com/donut-party/datapotato][datapotato]] :: Schema-based test data generation
- [[https://github.com/adamrenklint/preo][preo]] :: Pre and post hooks for function args and return values..

** Interesting alternatives
- [[https://github.com/hyperfiddle/electric][electric]] :: For frontend/backend sync? Looks very interesting, but a quite different approach (i.e. not something to integrate with the rest of this stack).
- re-frame :: Using refx currently as that seemed to be more appropriate with uix / modern react (based on some naive/shallow reading a few months back), however re-frame is the reference / more actively developed and has useful development aids (e.g. re-frame-10x, re-frame-flow), so likely worth taking a look at. It also works with uix, apparently.

** Investigated / not adopted
- Clojure [[https://clojure.org/guides/spec][spec]] :: selective strict typing / design-by-contract and for generative testing. Used this initially, but moved to malli - primarily because syntax easier to parse visually (matches data structure).

** AWS integration
This project includes some (now disabled -- see below) integration with AWS via amplify.
Initially used the =@aws-amplify/ui-react= package to provide their auth component, which is pretty bloated -- including just the auth component makes the build jump from 275 files to 1243 files.

In fact I think I'll look at supabase before spending more time on this - not loving the AWS amplify experience to date.

The required AWS libs are still referenced in [[./package.json]] for now...
To re-enable, just uncomment the relevant lines in [[./src/cljserial/core.cljs]]

*** Services to integrate
- [X] Amplify (meta/configuration)
- [X] Cognito (auth)
- [ ] S3 (file storage)

*** References
- [[https://www.arthurbrrs.me/pre-signed-s3-clojurescript.html][Pre-signed uploads to AWS S3 using Clojure(script)]] :: Excellent clear (and detailed) blog post from 2022 on uploads to AWS S3, using re-frame coeffects etc.

*** AWS local environment setup
For instructions on setting up your amplify environment, see here: https://docs.amplify.aws/react/tools/cli/start/set-up-cli/

This is required to generate the aws-exports.js needed for the build.

*** AWS dependency patching / post-installation steps
A couple of the aws dependencies have some post-installation steps -- a script has been provided to automate this:
[[./patch-aws-dependencies.sh]]

This should be run...
1. After running ~yarn install~.
2. After updating the =@aws-amplify/ui-react= package.

* Language/library references
(Don't judge me, I'm a C programmer)
- [[https://day8.github.io/re-frame/][re-frame docs]] :: Excellent reference for re-fx, and general overview of state management in front-end development
- [[https://cljs.info/cheatsheet/][CLJS cheat sheet]]
- [[https://nerdcave.com/tailwind-cheat-sheet][Tailwind cheat sheet]]
- [[https://www.learn-clojurescript.com][Learn Clojurescript]]
- [[https://github.com/bbatsov/clojure-style-guide][Clojure style guide]] :: Wot it says on the tin....
- [[https://daisyui.com/components/][DaisyUI Components]]

* Blog posts etc.
Other peoples experience of working with clojure/clojurescript stacks...
- [[https://whimsical.com/blog/how-we-built-whimsical]] :: clojure-based shop doing visual collaboration software. New home of Roman Liutikov (UIX author)

* Component / style resources
- [[http://html2hiccup.buttercloud.com/][html->hiccup converter]] :: TODO - fork this for uix syntax? See https://github.com/buttercloud/html2hiccup

* Build cheatsheet

** Dependencies
The majority of these are handled by via:
- [[./flake.nix]]
- [[./deps.edn]]
- [[./package.json]]

In addition, fontawesome is required at build time to unpack svg for icons. This can be downloaded into your source tree by executing the snippet below (from [[https://github.com/cjohansen/fontawesome-clj]]):

#+begin_src sh
  clojure -Sdeps "{:deps {no.cjohansen/fontawesome-clj {:mvn/version \"2023.10.26\"} \
                        clj-http/clj-http {:mvn/version \"3.12.3\"} \
                        hickory/hickory {:mvn/version \"0.7.1\"}}}" \
  -M -m fontawesome.import :download resources 6.4.2
#+end_src

#+RESULTS:

** Source materials
- [[https://github.com/pitch-io/uix-starter][uix-starter]] for initial UIx2/shadow-cljs setup

** Initial setup
#+begin_src shell
yarn install # install NPM deps
yarn dev # run dev build in watch mode with CLJS REPL
#+end_src

** Test build
A shadow-cljs job has been setup to watch the test/src tree for changes and display results in the browser.
Per [[https://shadow-cljs.github.io/docs/UsersGuide.html#_testing]].

#+begin_src shell
  yarn test
#+end_src

Open [[http://localhost:8081]] for test results.

** Component-driven development (portfolio) build
N.B. Currently we need to run either portfolio or the app -- there's probably a way to do both...

#+begin_src shell
yarn portfolio
#+end_src

** Production build
#+begin_src shell
yarn release # build production bundle
#+end_src

** Combined development build (dev app, unit test runner and portfolio)

#+begin_src shell
yarn all
#+end_src

#+RESULTS:

** shadow-cljs inspect
shadow-cljs includes a browser based interface allowing the runtime (function defs and data) to be inspected and modified -- effectively a GUI for the REPL.
Accessible at http://localhost:9630

* Repl cheatsheet
See [[https://shadow-cljs.github.io/docs/UsersGuide.html#_clojurescript_repl]]

** Open a repl session from a shell

To open a repl session from a shell prompt
#+begin_src shell
  npx shadow-cljs cljs-repl app
#+end_src

** Open a repl session from your editor
Currently using Emacs/Cider.
The [[https://docs.cider.mx][docs]] provided for [[https://cider.mx/][cider]] are excellent. Read them.

* Documenting code
- Clojure doc strings support markdown syntax (i.e. can include tables and code examples)
- Refer to function arguments using backticks.
- Refer to other functions using wikilink syntax '[[]]'.

See example below

#+begin_src clojure
  (defn do-something [] ... )

  (defn do-something-else
    "Do something `n-times` times. See also [[do-something]]."
    [n-times]
    ....)
#+end_src

See short but sweet blog post by Martin Klepsch [[https://martinklepsch.org/posts/writing-awesome-docstrings.html][here]].

* Stack components

** State management

*** Application data storage using refx (re-frame)
Using refx (re-frame without reagent) as a centralised app state store.
- re-frame [[https://github.com/day8/re-frame][on github]] / [[https://day8.github.io/re-frame/][docs]] :: Overview of concepts etc.
- [[https://github.com/ferdinand-beyer/refx]] :: Includes some brief if excellent documentation / examples provided by the author.
- [[https://vvvvalvalval.github.io/posts/some-re-frame-patterns-for-composability.html][re-frame patterns for composability]] :: Nice post on patterns for parameterising events and subscriptions (rather than hard-coding app-db paths and event IDs etc.) for composability.

Also using clojure.spec to define a schema for application state -- validated per database update using refx interceptors (based on refx example).
This approach may be heavyweight in practice, but a nice demonstration of the capabilities.

*** Hierarchical state machines using cljs-statecharts
The intent is to model high-level application state using one or more statemachines.
See [[./src/cljserial/hsm_refx.cljs]] for some code integrating refx and cljs-statecharts.
See [[./src/cljserial/state/serial_states.cljs]] for a usage example.

** Testing

*** Generative testing using Spec and Spec test

**** Links
- [[https://clojure.org/about/spec][clojure.spec - Rationale and Overview]] :: Official docs.
- [[https://corfield.org/blog/2019/09/13/using-spec/][How do you use clojure.spec]] :: By Sean Corfield - very knowledgeable clojure contributor.
- [[https://www.juxt.pro/blog/generative-ui-clojure-spec/][JUXT / Generative UI testing with clojure.spec]] :: Useful very short post

*** Candidate approaches

**** cljs.test and react-testing-library
Sounds promising -- see here:
- https://francisvitullo.medium.com/a-way-of-testing-views-in-clojurescript-apps-98aaf57c5c2a
- https://gist.github.com/cdbkr/f195d7fbb600fae9655f37e7b2b4813e

This guy does something similar, but bypassing use of react-testing-library:
- https://www.arthurbrrs.me/testing-the-dom-using-shadow-and-reagent

** CSS
- TailwindCSS and PostCSS integrated following instructions [[https://curiousprogrammer.dev/blog/how-can-i-use-tailwind-in-my-clojure-script-web-app][here]]

*** DaisyUI / Portfolio CSS incompatibility
If portfolio is injecting itself into the app index.html (which references the generated tailwind.css directly), the styles make the Portfolio navigation panel unreadable (Portfolio usually injects the styles into the iframe displaying your scenes rather than the root -- I think).

To workaround this, the portfolio dev server uses a different index.html, but the app "public/css" folder is included in the dev server paths. This ensures we're picking up production css without having to duplicate the css watch task. It just means that we reference "css/tailwind.css" from the app's [[./public/index.html]] and "/tailwind.css" from [[./portfolio/resources/public/index.html]].

** Internationalisation
Watch this space. Some of the tooling uses keys / cljs dictionaries -- would rather something gettext / po file based.

*** clj-18n
https://github.com/puppetlabs/clj-i18n

This mentions clojure and lein only - not immediately clear to me whether viable for clojurescript project.

*** tempura
https://github.com/taoensso/tempura

This prefers using keys at the point of use rather than just using the string itself as the key (the GNU gettext / .po-file tooling I'm used to from python work).
It does allow the use of plain (fallback) strings during development, but requires insertion of keys for lookup later -- which seems laborious / inelegant.
